DROP TABLE driver_vehicle;
DROP TABLE driver;
DROP TABLE vehicle;
DROP TABLE brand;
DROP TABLE enterprise;
DROP TABLE enterprise_manager;
DROP TABLE manager;
DROP TABLE person;

DELETE FROM driver_vehicle;
DELETE FROM driver;
DELETE FROM vehicle;
ALTER SEQUENCE vehicle_id_seq RESTART WITH 1;
ALTER SEQUENCE driver_id_seq RESTART WITH 1;

CREATE TABLE brand (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	type_vehicle varchar(50) NOT NULL,
	tank_capacity double precision NOT NULL,
	load_capacity double precision NOT NULL,
	passenger_capacity int NOT NULL,
	engine_power double precision NOT NULL
);

CREATE TABLE enterprise (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	city varchar(50) NOT NULL,
	phone varchar(50) NOT NULL
);

CREATE TABLE vehicle (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	registration_number varchar(9) NOT NULL,
	year_of_production int NOT NULL,
	price double precision NOT NULL,
	mileage double precision NOT NULL,
	brand_id int REFERENCES brand(id) ON DELETE SET NULL,
	enterprise_id int REFERENCES enterprise(id) ON DELETE SET NULL
);

CREATE TABLE driver (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	salary double precision NOT NULL,
	enterprise_id int REFERENCES enterprise(id) ON DELETE SET NULL,
	is_active boolean DEFAULT FALSE,
	active_vehicle_id int UNIQUE REFERENCES vehicle(id) ON DELETE CASCADE
);

CREATE TABLE driver_vehicle (
	driver_id int REFERENCES driver(id) ON DELETE SET NULL,
	vehicle_id int REFERENCES vehicle(id) ON DELETE SET NULL,
	PRIMARY KEY(driver_id, vehicle_id)
);

INSERT INTO brand (name, type_vehicle, tank_capacity, load_capacity, passenger_capacity, engine_power) VALUES ('Scania', 'BUS', 105, 500, 35, 200);
INSERT INTO brand (name, type_vehicle, tank_capacity, load_capacity, passenger_capacity, engine_power) VALUES ('Man', 'TRUCK', 155, 500, 3, 220);
INSERT INTO brand (name, type_vehicle, tank_capacity, load_capacity, passenger_capacity, engine_power) VALUES ('Lada', 'PASSENGER_CAR', 85, 300, 5, 100);

INSERT INTO enterprise (name, city, phone) VALUES ('Машина мечты','Иваново', '3513');
INSERT INTO enterprise (name, city, phone) VALUES ('Прокат ТС','Суздаль', '4848');
INSERT INTO enterprise (name, city, phone) VALUES ('С ветерком','Углич', '7321');


CREATE TABLE person (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username varchar(50) NOT NULL,
	password varchar NOT NULL,
	role varchar(100)
);

INSERT INTO person (username, password, role) VALUES ('manager1', '$2a$10$YFVdDAgSEPcY7kUzI0N8d.kUFvmF4gOfEOmX0ZlzMsIVozqmO0wMO', '');
INSERT INTO person (username, password, role) VALUES ('manager2', '$2a$10$ivCWUYla7sdak/BeFj/yLOOlln4VIjrZd9wb.jta3nYh84uKJf2X.', '');
UPDATE person set role='ROLE_MANAGER1' WHERE id=1;
UPDATE person set role='ROLE_MANAGER2' WHERE id=2;


CREATE TABLE manager (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username varchar(50) NOT NULL,
	password varchar NOT NULL
);

INSERT INTO manager (username, password) VALUES ('manager1', '$2a$10$YFVdDAgSEPcY7kUzI0N8d.kUFvmF4gOfEOmX0ZlzMsIVozqmO0wMO');
INSERT INTO manager (username, password) VALUES ('manager2', '$2a$10$ivCWUYla7sdak/BeFj/yLOOlln4VIjrZd9wb.jta3nYh84uKJf2X.');

CREATE TABLE enterprise_manager (
	enterprise_id int REFERENCES enterprise(id) ON DELETE SET NULL,
	manager_id int REFERENCES manager(id) ON DELETE SET NULL,
	PRIMARY KEY(enterprise_id, manager_id)
);

INSERT INTO enterprise_manager (enterprise_id, manager_id) VALUES (1, 1);
INSERT INTO enterprise_manager (enterprise_id, manager_id) VALUES (2, 1);
INSERT INTO enterprise_manager (enterprise_id, manager_id) VALUES (2, 2);
INSERT INTO enterprise_manager (enterprise_id, manager_id) VALUES (3, 2);

SELECT * FROM enterprise;
SELECT * FROM manager;
SELECT * FROM enterprise_manager;

SELECT * FROM vehicle;
SELECT * FROM driver;
SELECT * FROM driver_vehicle;

SELECT last_value FROM vehicle_id_seq;
ALTER SEQUENCE vehicle_id_seq RESTART WITH 12000;

