DROP TABLE vehicle;
DROP TABLE brand;

CREATE TABLE brand (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	type_vehicle varchar(50) NOT NULL,
	tank_capacity double precision NOT NULL,
	load_capacity double precision NOT NULL,
	passenger_capacity int NOT NULL,
	engine_power double precision NOT NULL
);

CREATE TABLE vehicle (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	registration_number varchar(9) NOT NULL,
	year_of_production int NOT NULL,
	price double precision NOT NULL,
	mileage double precision NOT NULL,
	brand_id int REFERENCES brand(id) ON DELETE SET NULL
);

INSERT INTO brand (name, type_vehicle, tank_capacity, load_capacity, passenger_capacity, engine_power) VALUES ('Scania', 'BUS', 105, 500, 35, 200);
INSERT INTO brand (name, type_vehicle, tank_capacity, load_capacity, passenger_capacity, engine_power) VALUES ('Man', 'TRUCK', 155, 500, 3, 220);
INSERT INTO brand (name, type_vehicle, tank_capacity, load_capacity, passenger_capacity, engine_power) VALUES ('Lada', 'PASSENGER_CAR', 85, 300, 5, 100);

INSERT INTO vehicle (registration_number, year_of_production, price, mileage, brand_id) VALUES ('A125CT163', 2000, 300000, 200, 1);
INSERT INTO vehicle (registration_number, year_of_production, price, mileage, brand_id) VALUES ('C548MK174', 2015, 400000, 100, 3);
INSERT INTO vehicle (registration_number, year_of_production, price, mileage, brand_id) VALUES ('A125CT102', 2020, 500000, 50, 3);

SELECT * FROM vehicle;
SELECT * FROM brand;


