DROP TABLE track;

CREATE TABLE track (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id int REFERENCES vehicle(id) ON DELETE SET NULL,
    coordinates GEOMETRY(Point, 4326),
    time_point varchar(50)
);

DROP TABLE trip;

CREATE TABLE trip (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id int REFERENCES vehicle(id) ON DELETE SET NULL,
    time_start varchar(50),
    time_end varchar(50),
    distance double precision
);

SELECT * FROM track;

SELECT * FROM trip;

SELECT p 
FROM track p 
WHERE p.vehicle_id = 1 
AND p.time_point = '2024/03/15 23:36' 
LIMIT 1
		
SELECT *
FROM track
WHERE p.vehicle_id = 1 
AND time_point = '2024/03/15 23:36'
ORDER BY id DESC
LIMIT 1
			
			
SELECT p FROM track p WHERE p.vehicle_id = 1 AND p.time_point = '2024/03/15 23:36' ORDER BY p.id ASC
			